/**
 * InsightsList — Container for AI-generated carbon reduction insights.
 *
 * Accessibility features:
 *   - <section aria-labelledby="insights-heading" aria-live="polite">
 *   - <ol aria-label="Personalized carbon reduction insights">
 *   - Gemini badge uses aria-label to explain the source
 *   - Total saving is announced via aria-live
 */

import type { InsightsResponse } from '../../types';
import { formatKg } from '../../utils/formatters';
import { InsightCard } from './InsightCard';
import { useCarbonStore } from '../../store/carbonStore';

interface InsightsListProps {
  insightsResponse: InsightsResponse;
}

export const InsightsList = ({ insightsResponse }: InsightsListProps) => {
  const { insights, source, total_potential_saving_kg } = insightsResponse;
  const saveEntry = useCarbonStore(s => s.saveEntry);

  return (
    <section
      aria-labelledby="insights-heading"
      aria-live="polite"
      aria-atomic="false"
      className="space-y-5 animate-slide-up"
    >
      {/* Header */}
      <div className="vercel-card p-6">
        <div className="flex items-start justify-between flex-wrap gap-3">
          <div>
            <h2 id="insights-heading" className="text-lg font-semibold text-slate-100 mb-1 tracking-tight">
              Your Personalised Reduction Plan
            </h2>
            <p className="text-sm text-slate-400">
              Targeting top emission sources with calculated reduction strategies.
            </p>
          </div>
          {source === 'gemini' && (
            <span
              aria-label="Insights powered by Google Gemini AI"
              className="
                inline-flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-wider
                bg-secondary-500/10 text-secondary-400 border border-secondary-500/20
                px-3 py-1.5 rounded-md
              "
            >
              <span aria-hidden="true" className="text-secondary-300">⚡</span>
              Powered by Google Gemini AI
            </span>
          )}
          {source === 'rules' && (
            <span
              aria-label="Insights generated by rule-based engine (Gemini AI unavailable)"
              className="
                inline-flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-wider
                bg-slate-800 text-slate-400 border border-slate-700
                px-3 py-1.5 rounded-md
              "
            >
              <span aria-hidden="true">🔧</span>
              Rule-based insights
            </span>
          )}
        </div>

        {/* Total Saving */}
        <div
          className="mt-5 pt-5 border-t border-slate-800/60 flex items-center gap-4"
          aria-label={`Total potential annual saving: ${formatKg(total_potential_saving_kg)} CO2e`}
        >
          <div className="text-3xl font-black text-primary-400 tabular-nums">
            {formatKg(total_potential_saving_kg)}
          </div>
          <div>
            <p className="text-sm font-medium text-slate-300">Total potential annual saving</p>
            <p className="text-xs text-slate-500">Assuming full implementation</p>
          </div>
        </div>
      </div>

      {/* Insights list - Bento Grid */}
      <ol
        aria-label="Personalized carbon reduction insights, ordered by priority"
        className="grid grid-cols-1 md:grid-cols-3 gap-4 list-none"
      >
        {insights.map((insight, i) => (
          <li key={i} className="flex">
            <InsightCard insight={insight} index={i} />
          </li>
        ))}
      </ol>

      {/* Save button */}
      <div className="flex justify-center pt-6">
        <button
          onClick={saveEntry}
          className="
            flex items-center gap-2 text-sm text-slate-300 border border-slate-700 bg-slate-900/50
            px-6 py-2.5 rounded-[10px] hover:bg-slate-800 hover:text-slate-100 hover:border-slate-600
            focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 focus:ring-offset-slate-950
            transition-all duration-200
          "
          aria-label="Save this carbon footprint snapshot to your history"
        >
          <span aria-hidden="true" className="text-primary-400">●</span>
          Commit to History
        </button>
      </div>
    </section>
  );
};
